# Generated by Django 4.2.16 on 2024-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=15, unique=True)),
                ('morada', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('localidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('www', models.URLField(blank=True)),
            ],
        ),
    ]
