# Generated by Django 4.2.16 on 2024-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdj_clientes', '0004_cliente_eticadata_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='morada1',
            new_name='morada',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='morada2',
        ),
        migrations.AddField(
            model_name='cliente',
            name='morada_secundaria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='eticadata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nif',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='www',
            field=models.URLField(blank=True, null=True),
        ),
    ]
