# Generated by Django 4.2.16 on 2024-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdj_clientes', '0006_remove_cliente_estado_cliente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
