# Generated by Django 4.2.16 on 2024-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('gerente', 'Gerente'), ('administrativo', 'Administrativo'), ('serralheiro', 'Serralheiro'), ('aprendiz_serralheiro', 'Aprendiz de Serralheiro'), ('fiel_armazem', 'Fiel de Armazém'), ('engenharia', 'Engenharia'), ('tecnico', 'Técnico')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('eticadata', models.IntegerField()),
                ('eticadata_armazem', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
