# Generated by Django 4.2.16 on 2024-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cc_costas',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/cc_costas/'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cc_frente',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/cc_frente/'),
        ),
    ]
