# Generated by Django 4.2.16 on 2024-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=15)),
                ('morada', models.CharField(max_length=255)),
                ('morada_secundaria', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('localidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('www', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('eticadata', models.IntegerField()),
            ],
        ),
    ]
