# Generated by Django 4.2.16 on 2024-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_cliente_cliente_desde_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=15)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('localidade', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
