# Generated by Django 4.2.16 on 2024-10-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_tipotrabalho_remove_obra_tipo_trabalho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='local',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='nome',
            field=models.CharField(default='sem nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.CharField(choices=[('orçamentada', 'Orçamentada'), ('adjudicada', 'Adjudicada'), ('em preparação', 'Em Preparação'), ('em execução', 'Em Execução'), ('pendente', 'Pendente'), ('concluída', 'Concluída'), ('fechada', 'Fechada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tipotrabalho',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
